### ISSUE TITLE
Does the API support requests of variants by institute?

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/loqusdbapi#1]
Nice app @moonso!
I'm working on [this](https://github.com/Clinical-Genomics/scout/issues/2295) Scout issue I'd like to set up the demo via docker-compose and use it to send requests from Scout. Works nicely btw.

I was wondering if I can run queries by institute. If not this issue transforms into a feature request! :)

**Comment by northwestwitch** [comment]
Or wait perhaps if you have different institutes you will have multiple IP addresses, one for each institute? I think this might be the case right? Sorry but it's the first time I work with loqusdb related code

**Comment by moonso** [comment]
Yes exactly @northwestwitch ! The institute specific databases are handled from Scout. So these will be independent instances of loqusdb running in parallel.
