### ISSUE TITLE
Docker image not pushed to Docker Hub on release event

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/loqusdbapi#13]
A new release event fails to push the Docker image to Docker Hub --> .github/workflows/dockerhub_push_release.yml

Last part of the action (build the image and push it) is the same as the other similar action triggered by a new PR, and that one works. Must be something related to when you create the release..

**Comment by northwestwitch** [comment]
I've tried to delete the new release and the tag. Looks like it's working now: https://github.com/Clinical-Genomics/loqusdbapi/actions

The Images are pushed to Docker Hub as well: https://hub.docker.com/repository/docker/clinicalgenomics/loqusdbapi

I'm not really sure why this time worked. Perhaps last time I've based the new release tag on a branch that didn't contain the github action? Anyway, it works so I'm closing the issue now!

**Comment by henrikstranneheim** [comment]
@northwestwitch Great!
