### ISSUE TITLE
Endpoint that returns loqusdb version?

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/loqusdbapi#2]
Working on the integration with Scout. Would be nice to have an endpoint of this app that returns the version of loqusdb (not of this app). Also because there is this check in Scout that loqus version should be >= 2.5. I need to skip version check when Scout connects using the loqusapi but perhaps returning a version (in the / endpoint?) isn't so complicated..

**Comment by moonso** [comment]
Sounds good and easy :)

**Comment by moonso** [comment]
You can skip that for now I guess

**Comment by northwestwitch** [comment]
I wrote a PR already, you could review and see if it's OK!
