### ISSUE TITLE
The app returns an HTTP error when the variant is not found

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/loqusdbapi#4]
And gives the impression that there is something wrong in the query, even if it's fine. Why not returning success (status code 200) and informing that the variant is not found? I've never used the loqus command line, but what does it return when the variant is not found?
I'm asking because API query errors in scout and in the vast majority of the other apps end up digested in a different way than successful responses with no results. Scout example:

https://github.com/Clinical-Genomics/scout/blob/dfec1c0c670c15f7e4babad75cf7a1261870c374/scout/utils/scout_requests.py#L64

**Comment by northwestwitch** [comment]
You could event return {}

**Comment by moonso** [comment]
When I read about REST I found that it is the common way to return a http error when a requested resource is not found. It could be discussed if **404 Not Found** or **204 No Content** suits better in this case but I think this is the correct way of doing it.

**Comment by moonso** [comment]
In this case it will be handled in the Loqusdbapi interaction so should not be a problem to handle right?

**Comment by northwestwitch** [comment]
It's not a problem to handle it in Scout, but it's more a philosophical question. Yes you get 404 when you don't find a resource but the resource is intended as a web page or file on the web server, not an entry in the database. The not found in the database is not an error, but a valid result.
I don't know, I would handle it differently, like returning the query executed and that you found no entries in the database..

**Comment by moonso** [comment]
Feel free to delve into the topic :) 

https://stackoverflow.com/questions/11746894/what-is-the-proper-rest-response-code-for-a-valid-request-but-an-empty-data

**Comment by northwestwitch** [comment]
@moonso your link says I'm right: 😄 

![image](https://user-images.githubusercontent.com/28093618/107366140-130f8400-6ade-11eb-893b-02f205273458.png)

**Comment by northwestwitch** [comment]
From the same response that was heavily upvoted:

![image](https://user-images.githubusercontent.com/28093618/107366892-f0ca3600-6ade-11eb-918c-b2647527e22d.png)

**Comment by moonso** [comment]
Well, I think that depends on how much of the text and answers you want to read

**Comment by moonso** [comment]
There is a comment from the author of the first answer:

```
@MatthewPatrickCashatt you're free to downvote as you please. I now finally understand why people are downvoting me, but the rationale is still wrong. When receiving a 404 it doesn't mean the route doesn't make sense, it means there is no resource at that location. Full stop. This is true if you're requesting /badurl or /user/9 when such a user doesn't exist. A developer can help by adding a better reason phrase than 'Not Found', but is not required to. – Chris Pfohl Sep 16 '16 at 17:26
```

**Comment by northwestwitch** [comment]
I still agree with the most upvoted answer. 404 is an error code and a record not found in a database is not an error, but a valid result. But if you like it this way is fine, I can fix Scout to handle the 404 error in a different way
