### ISSUE TITLE
fuse-overlayfs use a lot of cpu using the latest version of the repo on podman cg-vm1

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/loqusdbapi#41]
<img width="649" alt="image" src="https://github.com/Clinical-Genomics/loqusdbapi/assets/28093618/199e5a60-e809-4d28-8ed7-fb749adc1322">

**Comment by dnil** [comment]
This is resolved by going back to an old release, `loqusdbapi-tumor@fix_docker_compose`

**Comment by northwestwitch** [comment]
The issue might be caused by:
- Fixes in this repo to unfreeze pymongo
- Fixes in loqusdb to unfreeze pymongo
- update of MongoDB from 4.4.9 to 7 (?)

**Comment by northwestwitch** [comment]
The version of loqus with the pymongo unfreeze was published on [Oct 27th](https://pypi.org/project/loqusdb/#history) in the afternoon:

<img width="383" alt="image" src="https://github.com/Clinical-Genomics/loqusdbapi/assets/28093618/89c09b3d-cdef-44c6-8987-69d0660ab623">

<hr>


The latest loqusdbapi version prod image was released on the same day, [but earlier](https://hub.docker.com/layers/clinicalgenomics/loqusdbapi/latest/images/sha256-04a7ccf07cfb1837ac8466dcf17e344156fc34205fabf0e93593dfd7b8a5e1f6?context=repo):

<img width="807" alt="image" src="https://github.com/Clinical-Genomics/loqusdbapi/assets/28093618/981f2a5a-fe74-40d8-8d95-103d1c62a549">

So it's case n.3, loqusdbapi still has the old loqusdb code without the fixes for mongodb v7 it seems

**Comment by dnil** [comment]
Good, that is the configuration we want to test for and get working, so all thumbs up. That didn't solve the problem though:
![Screenshot 2023-11-10 at 11 45 52](https://github.com/Clinical-Genomics/loqusdbapi/assets/758570/55a53871-5d32-421c-839e-b040d57b0638)

The issue does not appear with the version from 2yrs back. (branch `fix_docker_compose`)

The log has a bit of threading issues. 
![Screenshot 2023-11-10 at 11 47 47](https://github.com/Clinical-Genomics/loqusdbapi/assets/758570/5980dde7-f5b5-44c2-bf0f-8f263f729ce7)

That could ofcourse have some other underlying issue. But we could start by checking threading lib versions / changes to that with new python?

**Comment by dnil** [comment]
Base image to one that supports current threading will be smooth, fingers crossed!
